### PR TITLE
remove lager as a dependency

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by joedevivo** [comment]
❤️

**Comment by phanimahesh** [comment]
There is not explanation as to why. Any specific reasons?

**Comment by tsloughter** [comment]
@phanimahesh for a lib like this it is best to not require a specific logger. I think this becomes particularly annoying for Elixir users who might want to use chatterbox.

**Comment by phanimahesh** [comment]
Okay. Yes, working with lager from elixir land is not exactly nice.

**Pull request merged**
